# Generated by Django 5.2.1 on 2025-07-16 19:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientOnboardingInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('street_address', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state_province', models.CharField(blank=True, max_length=50)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(default='USA', max_length=100)),
                ('retirement_age', models.IntegerField(blank=True, null=True)),
                ('monthly_income', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('risk_tolerance', models.CharField(blank=True, choices=[('conservative', 'Conservative'), ('moderate', 'Moderate'), ('aggressive', 'Aggressive')], max_length=20)),
                ('investment_goals', models.JSONField(blank=True, default=list)),
                ('investment_timeframe', models.CharField(blank=True, choices=[('short', 'Short-term (0-3 years)'), ('medium', 'Medium-term (3-10 years)'), ('long', 'Long-term (10+ years)')], max_length=20)),
                ('investable_assets', models.CharField(blank=True, choices=[('under100k', 'Under $100,000'), ('100k-250k', '$100,000 - $250,000'), ('250k-500k', '$250,000 - $500,000'), ('500k-1m', '$500,000 - $1,000,000'), ('1m-5m', '$1,000,000 - $5,000,000'), ('over5m', 'Over $5,000,000')], max_length=20)),
                ('special_considerations', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AddressMismatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_id', models.CharField(max_length=100)),
                ('file_name', models.CharField(max_length=200)),
                ('client_street', models.CharField(blank=True, max_length=200)),
                ('client_city', models.CharField(blank=True, max_length=100)),
                ('client_state', models.CharField(blank=True, max_length=50)),
                ('client_postal_code', models.CharField(blank=True, max_length=20)),
                ('client_full_address', models.TextField(blank=True)),
                ('extracted_street', models.CharField(blank=True, max_length=200)),
                ('extracted_city', models.CharField(blank=True, max_length=100)),
                ('extracted_state', models.CharField(blank=True, max_length=50)),
                ('extracted_postal_code', models.CharField(blank=True, max_length=20)),
                ('extracted_full_address', models.TextField(blank=True)),
                ('mismatch_type', models.CharField(choices=[('full_mismatch', 'Complete Address Mismatch'), ('partial_mismatch', 'Partial Address Mismatch'), ('not_validated', 'Address Not Validated')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address_mismatches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('client', 'file_id')},
            },
        ),
    ]
